### CAPSTONE PROJECT ON PANDAS AND DATABASES
#### With Oghenevwarhe & Nicholas
#### FastDeliver Nigeria

In [10]:
import pandas as pd

##### Read the raw CSV

In [11]:
# 1.    Load Dataset

orders_table = pd.read_csv(r'C:\Users\vwarhe\Documents\GitHub\fastdeliver_nigeria_capstone\Data\fastdeliver_orders.csv')
print("Orders Table loaded into Panda DataFrame")

Orders Table loaded into Panda DataFrame

In [12]:
#   b.Data Exploration
print(f"The shape of the orders table is: ", orders_table.shape)

The shape of the orders table is:  (500, 13)

In [13]:
print(f"The Statistics for numeric columns are as follows: \n"
      , orders_table.describe())

The Statistics for numeric columns are as follows:
        delivery_fee  rider_rating
count    500.000000    430.000000
mean     711.795560      3.690233
std      293.155217      0.711673
min      200.040000      2.500000
25%      455.642500      3.100000
50%      729.575000      3.700000
75%      968.467500      4.300000
max     1196.370000      5.000000

In [14]:
print(f"Orders table information: ")
orders_table.info()

Orders table information:

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        500 non-null    str
 1   customer_name   500 non-null    str
 2   pickup_zone     500 non-null    str
 3   delivery_zone   500 non-null    str
 4   rider_id        500 non-null    str
 5   order_date      500 non-null    str
 6   pickup_time     368 non-null    str
 7   delivery_time   242 non-null    str
 8   order_value     480 non-null    str
 9   delivery_fee    500 non-null    float64
 10  status          500 non-null    str
 11  payment_method  454 non-null    str
 12  rider_rating    430 non-null    float64
dtypes: float64(2), str(11)
memory usage: 50.9 KB

In [15]:
# c.    checking for null values
print(f"Number of null values: \n", orders_table.isnull().sum())

Number of null values:
 order_id            0
customer_name       0
pickup_zone         0
delivery_zone       0
rider_id            0
order_date          0
pickup_time       132
delivery_time     258
order_value        20
delivery_fee        0
status              0
payment_method     46
rider_rating       70
dtype: int64

In [16]:
# d.    check for duplicate rows
print(f"Number of duplicate rows: \n", orders_table.duplicated().sum())

Number of duplicate rows:
 40

In [17]:
# e.    Checking for unique values
orders_table['delivery_time'].unique()
print(f"View Unique Values: \n", orders_table.head(10))

View Unique Values:
    order_id      customer_name      pickup_zone    delivery_zone rider_id  \
0  FD-00029       Fatima Bello         Surulere            Ikeja  RDR-023
1  FD-00257  Ifeanyi Nwachukwu             Yaba            Ojodu  RDR-030
2  FD-00277      Segun Balogun  Victoria Island            Lekki  RDR-025
3  FD-00301     Obinna Okonkwo         Surulere            Lekki  RDR-009
4  FD-00423        Chidi Okeke            Ojodu            Ikeja  RDR-029
5  FD-00132  Babatunde Oluwole            Ikeja            Lekki  RDR-008
6  FD-00124   Zainab Abdullahi            Ikeja            Lekki  RDR-018
7  FD-00214     Obinna Okonkwo            Ikeja            Lekki  RDR-025
8  FD-00358       Patience Eze            Lekki            Ikeja  RDR-011
9  FD-00177       Emeka Chukwu            Ojodu  Victoria Island  RDR-015

   order_date pickup_time delivery_time order_value  delivery_fee      status  \
0  2026-07-28       13:31         14:45     6137.01        844.62   DELIVERED
1  2026-07-28       12:26         13:53    13387.28        508.26  Delivered
2  2026-07-01       09:21         09:52     13881.6       1183.82   delivered
3  2026-07-16       14:31         15:19  ₦10,627.49       1165.94   delivered
4  2026-07-23       13:19           NaN    13464.73        327.81      Failed
5  2026-07-16       16:34         17:31     4232.26        245.72      failed
6  2026-07-15       17:03         18:15     14225.1        993.73  Delivered
7  2026-07-19       20:05           NaN     ₦826.48        346.43   delivered
8  2026-07-25         NaN           NaN    11317.17        691.02  Delivered
9  2026-07-22         NaN           NaN    11455.31       1024.21   Delivered

  payment_method  rider_rating
0           card           2.7
1       transfer           2.7
2            NaN           3.5
3       transfer           2.8
4           card           4.4
5           cash           4.6
6       transfer           2.8
7       transfer           NaN
8           cash           3.2
9           card           3.5

#### Fix missing delivery times

In [18]:
# Convert delivery_time from string to time
# Keep the original data
orders_table['delivery_time_original'] = orders_table['delivery_time']

# Clean the delivery_time column
orders_table['delivery_time'] = pd.to_datetime(
    orders_table['delivery_time_original'],
    errors='coerce'
).dt.time

# Check missing values
print(
    f"There are {orders_table['delivery_time'].isna().sum()} null orders"
)

There are 258 null orders

C:\Users\vwarhe\AppData\Local\Temp\ipykernel_20424\3627574593.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  orders_table['delivery_time'] = pd.to_datetime(

In [19]:
# Find the most common delivery time
most_common_time = orders_table['delivery_time'].mode()[0]

# Fill missing values
orders_table['delivery_time'] = orders_table['delivery_time'].fillna(most_common_time)

In [20]:
# Check the result

separator = "═" * 48
print(separator)
print(f"{'FASTDELIVER NIGERIA — REPORT':^48}")
print(separator)


print("Missing Delivery Times have been fixed and updated")
print(orders_table['delivery_time'].dtype)
print(orders_table['delivery_time'].isna().sum())

════════════════════════════════════════════════
          FASTDELIVER NIGERIA — REPORT
════════════════════════════════════════════════
Missing Delivery Times have been fixed and updated
object
0

In [21]:
orders_table.head(20)
orders_table['delivery_time'].unique

<bound method Series.unique of 0      14:45:00
1      13:53:00
2      09:52:00
3      15:19:00
4      10:28:00
         ...
495    10:28:00
496    16:29:00
497    10:28:00
498    10:28:00
499    13:38:00
Name: delivery_time, Length: 500, dtype: object>

In [22]:
orders_table['order_id'].duplicated().sum()

np.int64(40)

#### Remove duplicate order IDs

In [23]:
# Removing duplicate rows

print(f"Shape BEFORE cleaning: {orders_table.shape}")
print(f"Missing delivery_time:    {orders_table['delivery_time'].isnull().sum()}")
print(f"Duplicate rows:        {orders_table.duplicated().sum()}")
print(f"order_id dtype:       {orders_table['order_id'].dtype}")
print()

# ── Step 1: Remove duplicates ─────────────────────────────────────────────
orders_table_clean = orders_table.drop_duplicates()
print(f"After drop_duplicates: {orders_table_clean.shape[0]} rows (removed {orders_table.shape[0] - orders_table_clean.shape[0]})")

Shape BEFORE cleaning: (500, 14)
Missing delivery_time:    0
Duplicate rows:        40
order_id dtype:       str

After drop_duplicates: 460 rows (removed 40)

In [24]:
orders_table_clean.info()

<class 'pandas.DataFrame'>
Index: 460 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                460 non-null    str
 1   customer_name           460 non-null    str
 2   pickup_zone             460 non-null    str
 3   delivery_zone           460 non-null    str
 4   rider_id                460 non-null    str
 5   order_date              460 non-null    str
 6   pickup_time             339 non-null    str
 7   delivery_time           460 non-null    object
 8   order_value             442 non-null    str
 9   delivery_fee            460 non-null    float64
 10  status                  460 non-null    str
 11  payment_method          416 non-null    str
 12  rider_rating            397 non-null    float64
 13  delivery_time_original  227 non-null    str
dtypes: float64(2), object(1), str(11)
memory usage: 53.9+ KB

In [25]:
# Convert pickup_time from string to time
orders_table['pickup_time'] = pd.to_datetime(
    orders_table['pickup_time'],
    errors='coerce'
).dt.time

# Check missing values
print(orders_table['pickup_time'].isna().sum())

132

C:\Users\vwarhe\AppData\Local\Temp\ipykernel_20424\3122136773.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  orders_table['pickup_time'] = pd.to_datetime(

In [26]:
orders_table.dtypes

order_id                      str
customer_name                 str
pickup_zone                   str
delivery_zone                 str
rider_id                      str
order_date                    str
pickup_time                object
delivery_time              object
order_value                   str
delivery_fee              float64
status                        str
payment_method                str
rider_rating              float64
delivery_time_original        str
dtype: object

In [27]:
# most common pickup time
most_pickup_time = orders_table_clean['pickup_time'].mode()[0]

# Fill missing values
orders_table_clean['pickup_time'] = orders_table['pickup_time'].fillna(most_pickup_time)

In [28]:
# convert order date to datetime format
orders_table_clean['order_date'] = pd.to_datetime(orders_table_clean['order_date'])

In [29]:
orders_table_clean['order_date'].head

<bound method NDFrame.head of 0     2026-07-28
1     2026-07-28
2     2026-07-01
3     2026-07-16
4     2026-07-23
         ...
495   2026-07-22
496   2026-07-19
497   2026-07-27
498   2026-07-03
499   2026-07-02
Name: order_date, Length: 460, dtype: datetime64[us]>

##### Convert order_value from strings to floats

In [30]:
# Removing currency sign
 
orders_table_clean['order_value'] = (
    orders_table_clean['order_value']
    .astype(str)
    .str.replace('₦', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

orders_table_clean['order_value'] = pd.to_numeric(orders_table_clean['order_value'], errors='coerce')

In [31]:
orders_table_clean.describe()

                       order_date   order_value  delivery_fee  rider_rating
count                         460    442.000000    460.000000    397.000000
mean   2026-07-15 08:45:54.782608   7947.280543    711.983609      3.684635
min           2026-07-01 00:00:00    826.480000    200.040000      2.500000
25%           2026-07-08 00:00:00   4612.777500    455.642500      3.100000
50%           2026-07-16 00:00:00   7852.710000    728.080000      3.700000
75%           2026-07-22 00:00:00  11686.682500    968.467500      4.300000
max           2026-07-28 00:00:00  14969.210000   1196.370000      5.000000
std                           NaN   4021.148160    292.571964      0.713429

In [32]:
orders_table_clean['order_value'].fillna(orders_table_clean['order_value'].median().round(2))

0       6137.01
1      13387.28
2      13881.60
3      10627.49
4      13464.73
         ...
495     3569.64
496     8316.14
497     3147.62
498     7836.38
499    10066.62
Name: order_value, Length: 460, dtype: float64

#### Standardise status values

In [33]:
# standardise status values
orders_table_clean['status'] = (
    orders_table_clean['status']
    .astype('string')
    .str.strip()
    .str.lower()
)

In [34]:
print(f"New status of orders table: \n", orders_table_clean['status'])
orders_table_clean.head()

New status of orders table:
 0      delivered
1      delivered
2      delivered
3      delivered
4         failed
         ...
495    delivered
496    delivered
497    delivered
498    delivered
499    delivered
Name: status, Length: 460, dtype: string

,order_id,customer_name,pickup_zone,delivery_zone,rider_id,order_date,pickup_time,delivery_time,order_value,delivery_fee,status,payment_method,rider_rating,delivery_time_original
0,FD-00029,Fatima Bello,Surulere,Ikeja,RDR-023,2026-07-28,13:31:00,14:45:00,6137.01,844.62,delivered,card,2.7,14:45
1,FD-00257,Ifeanyi Nwachukwu,Yaba,Ojodu,RDR-030,2026-07-28,12:26:00,13:53:00,13387.28,508.26,delivered,transfer,2.7,13:53
2,FD-00277,Segun Balogun,Victoria Island,Lekki,RDR-025,2026-07-01,09:21:00,09:52:00,13881.60,1183.82,delivered,NaN,3.5,09:52
3,FD-00301,Obinna Okonkwo,Surulere,Lekki,RDR-009,2026-07-16,14:31:00,15:19:00,10627.49,1165.94,delivered,transfer,2.8,15:19
4,FD-00423,Chidi Okeke,Ojodu,Ikeja,RDR-029,2026-07-23,13:19:00,10:28:00,13464.73,327.81,failed,card,4.4,NaN

In [35]:
orders_table_clean['payment_method'].isna().sum()

np.int64(44)

In [36]:
# Filling missing values in payment method

orders_table_clean["payment_method"] = orders_table_clean["payment_method"].fillna("not_documented")

print(f"Updated Payment methods below: \n",orders_table_clean['payment_method'].head(20))

Updated Payment methods below:
 0               card
1           transfer
2     not_documented
3           transfer
4               card
5               cash
6           transfer
7           transfer
8               cash
9               card
10    not_documented
11              card
12    not_documented
13              cash
14              cash
15              card
16              card
17              cash
18              card
19              cash
Name: payment_method, dtype: str

In [37]:
# checking rider ratings for statistical readings

orders_table_clean['rider_rating'].describe()

count    397.000000
mean       3.684635
std        0.713429
min        2.500000
25%        3.100000
50%        3.700000
75%        4.300000
max        5.000000
Name: rider_rating, dtype: float64

In [38]:
# Replacing null values

orders_table_clean['rider_rating'] = orders_table_clean['rider_rating'].fillna(  
    orders_table_clean['rider_rating'].mean())

In [39]:
print(f"Updated Rider ratings: \n", orders_table_clean['rider_rating'])

Updated Rider ratings:
 0      2.7
1      2.7
2      3.5
3      2.8
4      4.4
      ...
495    3.6
496    4.4
497    3.2
498    3.2
499    3.7
Name: rider_rating, Length: 460, dtype: float64

In [40]:
orders_table_clean['rider_rating'].isna().sum()

np.int64(0)

##### Build the analytical pipeline

In [41]:
# Zone with highest revenue
zone_summary = (
    orders_table_clean
    .groupby("delivery_zone")
    .agg(
        total_revenue=("order_value", "sum"),
        order_count=("order_id", "count"),
        avg_order_value=("order_value", "mean")
    )
    .sort_values("total_revenue", ascending=False)
    .reset_index()
)
print(f"Zone summary: \n{zone_summary}")

revenue_by_zone = orders_table_clean.groupby("delivery_zone")["order_value"].sum()

top_zone = revenue_by_zone.idxmax()
top_revenue = revenue_by_zone.max()

print(f"The delivery zone that generates the most revenue is {top_zone}, with ₦{top_revenue:,.2f} in total revenue.")

Zone summary:
     delivery_zone  total_revenue  order_count  avg_order_value
0            Ojodu      660348.63           86      7768.807412
1         Surulere      652229.83           84      8052.220123
2            Lekki      617973.53           79      7922.737564
3            Ikeja      585483.33           74      8364.047571
4  Victoria Island      528268.60           72      7884.605970
5             Yaba      468394.08           65      7678.591475
The delivery zone that generates the most revenue is Ojodu, with ₦660,348.63 in total revenue.

In [42]:
# Pick up zone with highest revenue
revenue_by_pickup_zone = orders_table_clean.groupby("pickup_zone")["order_value"].sum()
top_pickup_zone = revenue_by_pickup_zone.idxmax()
top_pickup_revenue = revenue_by_pickup_zone.max()

print(f"The pickup zone that generates the most revenue is {top_pickup_zone}, with ₦{top_pickup_revenue:,.2f} in total revenue.")

The pickup zone that generates the most revenue is Victoria Island, with ₦710,608.87 in total revenue.

In [43]:
# Total revenue by zone
orders_table_clean["total_revenue"] = orders_table_clean["order_value"] + orders_table_clean["delivery_fee"]

revenue_by_zone = (
    orders_table_clean
    .groupby("delivery_zone")["total_revenue"]
    .sum()
    .sort_values(ascending=False)
)

print("TOTAL REVENUE BY ZONE (order value + delivery fee)")
print("-" * 50)
for zone, revenue in revenue_by_zone.items():
    print(f"{zone:<20} {revenue:>15,.2f}")

print()
top_zone = revenue_by_zone.idxmax()
top_revenue = revenue_by_zone.max()
print(f"→ Highest total revenue: {top_zone} ({top_revenue:,.2f})")

TOTAL REVENUE BY ZONE (order value + delivery fee)
--------------------------------------------------
Ojodu                     717,933.31
Surulere                  714,531.38
Lekki                     668,482.33
Ikeja                     638,027.93
Victoria Island           576,232.89
Yaba                      512,799.19

→ Highest total revenue: Ojodu (717,933.31)

In [44]:
# Highest failure rate by rider
failure_rate_by_rider = (
    orders_table_clean
    .groupby("rider_id")["status"]
    .apply(lambda x: (x == "failed").mean() * 100)
    .sort_values(ascending=False)
)

print(failure_rate_by_rider.head(10).round(1).astype(str) + "%")
print(f"→ The rider with the highest failure rate is {failure_rate_by_rider.idxmax()} with a failure rate of {failure_rate_by_rider.max():.1f}%.")

rider_id
RDR-003    40.0%
RDR-002    33.3%
RDR-008    33.3%
RDR-019    33.3%
RDR-021    31.2%
RDR-004    30.0%
RDR-027    28.6%
RDR-023    26.7%
RDR-029    26.3%
RDR-013    25.0%
Name: status, dtype: str
→ The rider with the highest failure rate is RDR-003 with a failure rate of 40.0%.

In [45]:
pickup = pd.to_datetime(orders_table_clean["pickup_time"].astype(str), errors="coerce")
delivery = pd.to_datetime(orders_table_clean["delivery_time"].astype(str), errors="coerce")

orders_table_clean["duration_min"] = (delivery - pickup).dt.total_seconds() / 60

avg_delivery_time = orders_table_clean.loc[orders_table_clean["duration_min"] >= 0, "duration_min"].mean()
print(f"Average delivery time: {avg_delivery_time:.1f} minutes")

Average delivery time: 41.8 minutes

C:\Users\vwarhe\AppData\Local\Temp\ipykernel_20424\1483204797.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pickup = pd.to_datetime(orders_table_clean["pickup_time"].astype(str), errors="coerce")
C:\Users\vwarhe\AppData\Local\Temp\ipykernel_20424\1483204797.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  delivery = pd.to_datetime(orders_table_clean["delivery_time"].astype(str), errors="coerce")

In [54]:
# Summary of orders by delivery zone, rider, and payment method
clean_orders_summary = (
    orders_table_clean
    .groupby(["delivery_zone", "rider_id", "payment_method"])
    .size()
    .reset_index(name="order_count")
)
print(clean_orders_summary)

    delivery_zone rider_id  payment_method  order_count
0           Ikeja  RDR-001            card            2
1           Ikeja  RDR-002            card            2
2           Ikeja  RDR-002  not_documented            2
3           Ikeja  RDR-002        transfer            1
4           Ikeja  RDR-003            cash            2
..            ...      ...             ...          ...
320          Yaba  RDR-028            cash            1
321          Yaba  RDR-029            cash            2
322          Yaba  RDR-030            card            1
323          Yaba  RDR-030  not_documented            1
324          Yaba  RDR-030        transfer            1

[325 rows x 4 columns]

In [47]:
avg_delivery_time_by_rider = (
    orders_table_clean
    [orders_table_clean["duration_min"] >= 0]
    .groupby("rider_id")["duration_min"]
    .mean()
    .sort_values(ascending=False)
    .reset_index(name="avg_delivery_time_min")
)

print(avg_delivery_time_by_rider.head(10))

  rider_id  avg_delivery_time_min
0  RDR-007              55.500000
1  RDR-013              53.888889
2  RDR-026              52.764706
3  RDR-028              51.777778
4  RDR-016              51.384615
5  RDR-008              50.000000
6  RDR-030              49.714286
7  RDR-005              49.636364
8  RDR-018              48.222222
9  RDR-025              47.400000

In [48]:
orders_table_clean

,order_id,customer_name,pickup_zone,delivery_zone,rider_id,order_date,pickup_time,delivery_time,order_value,delivery_fee,status,payment_method,rider_rating,delivery_time_original,total_revenue,duration_min
0,FD-00029,Fatima Bello,Surulere,Ikeja,RDR-023,2026-07-28,13:31:00,14:45:00,6137.01,844.62,delivered,card,2.7,14:45,6981.63,74.0
1,FD-00257,Ifeanyi Nwachukwu,Yaba,Ojodu,RDR-030,2026-07-28,12:26:00,13:53:00,13387.28,508.26,delivered,transfer,2.7,13:53,13895.54,87.0
2,FD-00277,Segun Balogun,Victoria Island,Lekki,RDR-025,2026-07-01,09:21:00,09:52:00,13881.60,1183.82,delivered,not_documented,3.5,09:52,15065.42,31.0
3,FD-00301,Obinna Okonkwo,Surulere,Lekki,RDR-009,2026-07-16,14:31:00,15:19:00,10627.49,1165.94,delivered,transfer,2.8,15:19,11793.43,48.0
4,FD-00423,Chidi Okeke,Ojodu,Ikeja,RDR-029,2026-07-23,13:19:00,10:28:00,13464.73,327.81,failed,card,4.4,NaN,13792.54,-171.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,FD-00121,Yetunde Akinwande,Ikeja,Lekki,RDR-019,2026-07-22,11:35:00,10:28:00,3569.64,676.04,delivered,card,3.6,NaN,4245.68,-67.0
496,FD-00341,Kelechi Uchenna,Ojodu,Lekki,RDR-016,2026-07-19,15:27:00,16:29:00,8316.14,1063.82,delivered,transfer,4.4,16:29,9379.96,62.0
497,FD-00449,Funmilayo Adeyemi,Surulere,Ikeja,RDR-015,2026-07-27,10:20,10:28:00,3147.62,801.41,delivered,transfer,3.2,NaN,3949.03,8.0
498,FD-00445,Biodun Okafor,Victoria Island,Lekki,RDR-010,2026-07-03,10:20,10:28:00,7836.38,956.47,delivered,transfer,3.2,NaN,8792.85,8.0
499,FD-00131,Chidi Okeke,Lekki,Ojodu,RDR-011,2026-07-02,12:20:00,13:38:00,10066.62,348.99,delivered,cash,3.7,13:38,10415.61,78.0

In [49]:
# Average delivery time
avg_delivery_time = (
    orders_table_clean.loc[orders_table_clean["duration_min"] >= 0, "duration_min"].mean()
)

print(f"Average delivery time: {avg_delivery_time:.2f} minutes")

Average delivery time: 41.77 minutes

In [50]:
orders_table_clean.dtypes

order_id                             str
customer_name                        str
pickup_zone                          str
delivery_zone                        str
rider_id                             str
order_date                datetime64[us]
pickup_time                       object
delivery_time                     object
order_value                      float64
delivery_fee                     float64
status                            string
payment_method                       str
rider_rating                     float64
delivery_time_original               str
total_revenue                    float64
duration_min                     float64
dtype: object

In [51]:
%pip install sqlalchemy psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\Users\vwarhe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.0.52)
Requirement already satisfied: psycopg2-binary in C:\Users\vwarhe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in C:\Users\vwarhe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\vwarhe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\vwarhe\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [52]:
from sqlalchemy import create_engine, text

In [ ]:
## ----- Connect to PostgreSQL Database -----
engine = create_engine(
    'postgresql://postgres:password@localhost:5432/fastdeliver')

print("Connected to PostgreSQL database")

## ---- Write the cleaned DataFrame to PostgreSQL
orders_table_clean.to_sql('orders_table_clean', engine, if_exists='replace', index=False)

clean_orders_summary.to_sql('clean_orders_summary', engine, if_exists='replace', index=False)

print ("Tables written to database: ")
with engine.connect() as conn:
    tables = ["orders_table_clean", "clean_orders_summary"]
    for tbl in tables:
        
        count = conn.execute(text(f"SELECT COUNT(*) FROM {tbl}")).fetchone()[0]
        print(f" {tbl:<12} {count:>10} rows")

Connected to PostgreSQL database
Tables written to database:
 orders_table_clean        460 rows
 clean_orders_summary        325 rows