### CAPSTONE PROJECT ON PANDAS AND DATABASES
#### With Oghenevwarhe & Nicholas
#### FastDeliver Nigeria

In [11]:
import pandas as pd

##### Read the raw CSV

In [12]:
# 1.    Load Dataset

orders_table = pd.read_csv(r'C:\Users\nicsparrow\OneDrive\Documents\10Alytics\Capstone Projects\fastdeliver_nigeria_capstone\Data\fastdeliver_orders.csv')
print("Orders Table loaded into Panda DataFrame")

Orders Table loaded into Panda DataFrame

In [13]:
#   b.Data Exploration
print(f"The shape of the orders table is: ", orders_table.shape)

The shape of the orders table is:  (500, 13)

In [14]:
print(f"The Statistics for numeric columns are as follows: \n"
      , orders_table.describe())

The Statistics for numeric columns are as follows:
        delivery_fee  rider_rating
count    500.000000    430.000000
mean     711.795560      3.690233
std      293.155217      0.711673
min      200.040000      2.500000
25%      455.642500      3.100000
50%      729.575000      3.700000
75%      968.467500      4.300000
max     1196.370000      5.000000

In [15]:
print(f"Orders table information: ")
orders_table.info()

Orders table information:
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        500 non-null    str
 1   customer_name   500 non-null    str
 2   pickup_zone     500 non-null    str
 3   delivery_zone   500 non-null    str
 4   rider_id        500 non-null    str
 5   order_date      500 non-null    str
 6   pickup_time     368 non-null    str
 7   delivery_time   242 non-null    str
 8   order_value     480 non-null    str
 9   delivery_fee    500 non-null    float64
 10  status          500 non-null    str
 11  payment_method  454 non-null    str
 12  rider_rating    430 non-null    float64
dtypes: float64(2), str(11)
memory usage: 50.9 KB

In [16]:
# c.    checking for null values
print(f"Number of null values: \n", orders_table.isnull().sum())

Number of null values:
 order_id            0
customer_name       0
pickup_zone         0
delivery_zone       0
rider_id            0
order_date          0
pickup_time       132
delivery_time     258
order_value        20
delivery_fee        0
status              0
payment_method     46
rider_rating       70
dtype: int64

In [17]:
# d.    check for duplicate rows
print(f"Number of duplicate rows: \n", orders_table.duplicated().sum())

Number of duplicate rows:
 40

In [18]:
# e.    Checking for unique values
orders_table['delivery_time'].unique()
print(f"View Unique Values: \n", orders_table.head(10))

View Unique Values:
    order_id      customer_name      pickup_zone    delivery_zone rider_id  \
0  FD-00029       Fatima Bello         Surulere            Ikeja  RDR-023
1  FD-00257  Ifeanyi Nwachukwu             Yaba            Ojodu  RDR-030
2  FD-00277      Segun Balogun  Victoria Island            Lekki  RDR-025
3  FD-00301     Obinna Okonkwo         Surulere            Lekki  RDR-009
4  FD-00423        Chidi Okeke            Ojodu            Ikeja  RDR-029
5  FD-00132  Babatunde Oluwole            Ikeja            Lekki  RDR-008
6  FD-00124   Zainab Abdullahi            Ikeja            Lekki  RDR-018
7  FD-00214     Obinna Okonkwo            Ikeja            Lekki  RDR-025
8  FD-00358       Patience Eze            Lekki            Ikeja  RDR-011
9  FD-00177       Emeka Chukwu            Ojodu  Victoria Island  RDR-015

   order_date pickup_time delivery_time order_value  delivery_fee      status  \
0  2026-07-28       13:31         14:45     6137.01        844.62   DELIVERED
1  2026-07-28       12:26         13:53    13387.28        508.26  Delivered
2  2026-07-01       09:21         09:52     13881.6       1183.82   delivered
3  2026-07-16       14:31         15:19  ₦10,627.49       1165.94   delivered
4  2026-07-23       13:19           NaN    13464.73        327.81      Failed
5  2026-07-16       16:34         17:31     4232.26        245.72      failed
6  2026-07-15       17:03         18:15     14225.1        993.73  Delivered
7  2026-07-19       20:05           NaN     ₦826.48        346.43   delivered
8  2026-07-25         NaN           NaN    11317.17        691.02  Delivered
9  2026-07-22         NaN           NaN    11455.31       1024.21   Delivered

  payment_method  rider_rating
0           card           2.7
1       transfer           2.7
2            NaN           3.5
3       transfer           2.8
4           card           4.4
5           cash           4.6
6       transfer           2.8
7       transfer           NaN
8           cash           3.2
9           card           3.5

#### Fix missing delivery times

In [19]:
# Convert delivery_time from string to time
# Keep the original data
orders_table['delivery_time_original'] = orders_table['delivery_time']

# Clean the delivery_time column
orders_table['delivery_time'] = pd.to_datetime(
    orders_table['delivery_time_original'],
    errors='coerce'
).dt.time

# Check missing values
print(
    f"There are {orders_table['delivery_time'].isna().sum()} null orders"
)

There are 258 null orders

C:\Users\nicsparrow\AppData\Local\Temp\ipykernel_24092\3627574593.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  orders_table['delivery_time'] = pd.to_datetime(

In [20]:
# Find the most common delivery time
most_common_time = orders_table['delivery_time'].mode()[0]

# Fill missing values
orders_table['delivery_time'] = orders_table['delivery_time'].fillna(most_common_time)

In [44]:
# Check the result

separator = "═" * 48
print(separator)
print(f"{'FASTDELIVER NIGERIA — REPORT':^48}")
print(separator)


print("Missing Delivery Times have been fixed and updated")
print(orders_table['delivery_time'].dtype)
print(orders_table['delivery_time'].isna().sum())

════════════════════════════════════════════════
          FASTDELIVER NIGERIA — REPORT
════════════════════════════════════════════════
Missing Delivery Times have been fixed and updated
object
0

In [22]:
orders_table.head(20)
orders_table['delivery_time'].unique

<bound method Series.unique of 0      14:45:00
1      13:53:00
2      09:52:00
3      15:19:00
4      10:28:00
         ...
495    10:28:00
496    16:29:00
497    10:28:00
498    10:28:00
499    13:38:00
Name: delivery_time, Length: 500, dtype: object>

In [24]:
orders_table['order_id'].duplicated().sum()

np.int64(40)

#### Remove duplicate order IDs

In [29]:
# Removing duplicate rows

print(f"Shape BEFORE cleaning: {orders_table.shape}")
print(f"Missing delivery_time:    {orders_table['delivery_time'].isnull().sum()}")
print(f"Duplicate rows:        {orders_table.duplicated().sum()}")
print(f"order_id dtype:       {orders_table['order_id'].dtype}")
print()

# ── Step 1: Remove duplicates ─────────────────────────────────────────────
orders_table_clean = orders_table.drop_duplicates()
print(f"After drop_duplicates: {orders_table_clean.shape[0]} rows (removed {orders_table.shape[0] - orders_table_clean.shape[0]})")

Shape BEFORE cleaning: (500, 14)
Missing delivery_time:    0
Duplicate rows:        40
order_id dtype:       str

After drop_duplicates: 460 rows (removed 40)

In [54]:
orders_table_clean.info()

<class 'pandas.DataFrame'>
Index: 460 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                460 non-null    str
 1   customer_name           460 non-null    str
 2   pickup_zone             460 non-null    str
 3   delivery_zone           460 non-null    str
 4   rider_id                460 non-null    str
 5   order_date              460 non-null    datetime64[us]
 6   pickup_time             460 non-null    object
 7   delivery_time           460 non-null    object
 8   order_value             442 non-null    float64
 9   delivery_fee            460 non-null    float64
 10  status                  460 non-null    string
 11  payment_method          460 non-null    str
 12  rider_rating            460 non-null    float64
 13  delivery_time_original  227 non-null    str
dtypes: datetime64[us](1), float64(3), object(2), str(7), string(1)
memory usage: 53.9+ KB

In [31]:
# Convert pickup_time from string to time
orders_table['pickup_time'] = pd.to_datetime(
    orders_table['pickup_time'],
    errors='coerce'
).dt.time

# Check missing values
print(orders_table['pickup_time'].isna().sum())

132

C:\Users\nicsparrow\AppData\Local\Temp\ipykernel_24092\3122136773.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  orders_table['pickup_time'] = pd.to_datetime(

In [32]:
# most common pickup time
most_pickup_time = orders_table_clean['pickup_time'].mode()[0]

# Fill missing values
orders_table_clean['pickup_time'] = orders_table['pickup_time'].fillna(most_pickup_time)

In [33]:
# convert order date to datetime format
orders_table_clean['order_date'] = pd.to_datetime(orders_table_clean['order_date'])

In [34]:
orders_table_clean['order_date'].head

<bound method NDFrame.head of 0     2026-07-28
1     2026-07-28
2     2026-07-01
3     2026-07-16
4     2026-07-23
         ...
495   2026-07-22
496   2026-07-19
497   2026-07-27
498   2026-07-03
499   2026-07-02
Name: order_date, Length: 460, dtype: datetime64[us]>

##### Convert order_value from strings to floats

In [35]:
# Removing currency sign
 
orders_table_clean['order_value'] = (
    orders_table_clean['order_value']
    .astype(str)
    .str.replace('₦', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

orders_table_clean['order_value'] = pd.to_numeric(orders_table_clean['order_value'], errors='coerce')

In [36]:
orders_table_clean.describe()

                       order_date   order_value  delivery_fee  rider_rating
count                         460    442.000000    460.000000    397.000000
mean   2026-07-15 08:45:54.782608   7947.280543    711.983609      3.684635
min           2026-07-01 00:00:00    826.480000    200.040000      2.500000
25%           2026-07-08 00:00:00   4612.777500    455.642500      3.100000
50%           2026-07-16 00:00:00   7852.710000    728.080000      3.700000
75%           2026-07-22 00:00:00  11686.682500    968.467500      4.300000
max           2026-07-28 00:00:00  14969.210000   1196.370000      5.000000
std                           NaN   4021.148160    292.571964      0.713429

In [ ]:
orders_table_clean['order_value'].fillna(orders_table_clean['order_value'].median().round(2))

#### Standardise status values

In [37]:
# standardise status values
orders_table_clean['status'] = (
    orders_table_clean['status']
    .astype('string')
    .str.strip()
    .str.lower()
)

In [41]:
print(f"New status of orders table: \n", orders_table_clean['status'])
orders_table_clean.head()

New status of orders table:
 0      delivered
1      delivered
2      delivered
3      delivered
4         failed
         ...
495    delivered
496    delivered
497    delivered
498    delivered
499    delivered
Name: status, Length: 460, dtype: string

,order_id,customer_name,pickup_zone,delivery_zone,rider_id,order_date,pickup_time,delivery_time,order_value,delivery_fee,status,payment_method,rider_rating,delivery_time_original
0,FD-00029,Fatima Bello,Surulere,Ikeja,RDR-023,2026-07-28,13:31:00,14:45:00,6137.01,844.62,delivered,card,2.7,14:45
1,FD-00257,Ifeanyi Nwachukwu,Yaba,Ojodu,RDR-030,2026-07-28,12:26:00,13:53:00,13387.28,508.26,delivered,transfer,2.7,13:53
2,FD-00277,Segun Balogun,Victoria Island,Lekki,RDR-025,2026-07-01,09:21:00,09:52:00,13881.60,1183.82,delivered,NaN,3.5,09:52
3,FD-00301,Obinna Okonkwo,Surulere,Lekki,RDR-009,2026-07-16,14:31:00,15:19:00,10627.49,1165.94,delivered,transfer,2.8,15:19
4,FD-00423,Chidi Okeke,Ojodu,Ikeja,RDR-029,2026-07-23,13:19:00,10:28:00,13464.73,327.81,failed,card,4.4,NaN

In [39]:
orders_table_clean['payment_method'].isna().sum()

np.int64(44)

In [47]:
# Filling missing values in payment method

orders_table_clean["payment_method"] = orders_table_clean["payment_method"].fillna("not_documented")

print(f"Updated Payment methods below: \n",orders_table_clean['payment_method'].head(20))

Updated Payment methods below:
 0               card
1           transfer
2     not_documented
3           transfer
4               card
5               cash
6           transfer
7           transfer
8               cash
9               card
10    not_documented
11              card
12    not_documented
13              cash
14              cash
15              card
16              card
17              cash
18              card
19              cash
Name: payment_method, dtype: str

In [48]:
# checking rider ratings for statistical readings

orders_table_clean['rider_rating'].describe()

count    397.000000
mean       3.684635
std        0.713429
min        2.500000
25%        3.100000
50%        3.700000
75%        4.300000
max        5.000000
Name: rider_rating, dtype: float64

In [49]:
# Replacing null values

orders_table_clean['rider_rating'] = orders_table_clean['rider_rating'].fillna(  
    orders_table_clean['rider_rating'].mean())

In [52]:
print(f"Updated Rider ratings: \n", orders_table_clean['rider_rating'])

Updated Rider ratings:
 0      2.7
1      2.7
2      3.5
3      2.8
4      4.4
      ...
495    3.6
496    4.4
497    3.2
498    3.2
499    3.7
Name: rider_rating, Length: 460, dtype: float64

In [53]:
orders_table_clean['rider_rating'].isna().sum()

np.int64(0)